
model_params:
  model: MultiHeadNet
  encoder_params:
    model: EfficientNet
    model_name: efficientnet-b3
    in_channels: 3
    num_classes: &hidden 512
  embedding_net_params:
    input_channels: *hidden
    hiddens: [512]
    layer_fn: {"module": "Linear", "bias": False}
    norm_fn: BatchNorm1d
    activation_fn: ReLU
    #dropout_fn: Dropout
    residual: "soft"

runner_params:
  input_key: image
  output_key: null

