model_params:
  model: MultiHeadNet
  encoder_params:
    arch: resnet18
    pretrained: True
    frozen: True
    pooling: MaxPool2d
    pooling_kwargs:
      kernel_size: 7      # [14, 7]
      stride: 7           # [14, 7]
  embedding_net_params:
    hiddens: [512]
    layer_fn: {"module": "Linear", "bias": False}
    norm_fn: BatchNorm1d
    activation_fn: ReLU
    dropout_fn: Dropout
    residual: "soft"

runner_params:
  input_key: image
  output_key: null

