shared:
  class_names: &class_names ['not_hotdog', 'hotdog']
  image_size: &image_size 224
  dataset_path: &dataset_path

model_params:
  image_size: *image_size
  heads_params:
    logits: &num_classes 2

args:
  expdir: src

stages:

  # train head
  data_params:
    num_workers: 5
    batch_size: 1
    #one_hot_classes: *num_classes NO ONE HOT
    in_csv_valid: data/preprocessed_test/test.csv
    datapath: data/preprocessed_test

  transform_params:

    transform: A.Compose
    transforms:
      - &pre_transforms
        transform: A.Compose
        transforms:
          - transform: A.LongestMaxSize
            max_size: *image_size
          - transform: A.PadIfNeeded
            min_height: *image_size
            min_width: *image_size
            border_mode: 0  # cv2.BORDER_CONSTANT
            value: 0
      - &post_transforms
        transform: A.Compose
        transforms:
          - transform: A.Normalize
          - transform: catalyst.ToTensor

  infer:
    callbacks_params:
      loss_class:
        callback: PredictionCallback
        path_key: filepath
        probs_key: logits

