shared:
  class_names: &class_names ['hotdog', 'not_hotdog']
  image_size: &image_size 224
  dataset_path: &dataset_path

model_params:
  image_size: *image_size
  heads_params:
    logits: &num_classes 2

args:
  expdir: src

stages:
  state_params:
    main_metric: &reduced_metric auc_class/_mean
    minimize_metric: False

  data_params:
    num_workers: 5
    batch_size: 8
    per_gpu_scaling: True
    one_hot_classes: *num_classes
    balance_strategy: upsampling
    in_csv_train: data/train/dataset_train.csv
    in_csv_valid: data/train/dataset_valid.csv
    datapath: data/train/

  transform_params:
    _key_value: True

    train:
      transform: A.Compose
      transforms:
        - &pre_transforms
          transform: A.Compose
          transforms:
            - transform: A.LongestMaxSize
              max_size: *image_size
            - transform: A.PadIfNeeded
              min_height: *image_size
              min_width: *image_size
              border_mode: 0  # cv2.BORDER_CONSTANT
              value: 0
        - &hard_transforms
          transform: A.Compose
          transforms:
            - transform: A.CoarseDropout
              max_holes: 4
              max_height: 56  # 224 // 4
              max_width: 56  # 224 // 4
            - transform: A.ShiftScaleRotate
              shift_limit: 0.1
              scale_limit: 0.1
              rotate_limit: 15
              border_mode: 2  # cv2.BORDER_REFLECT
            - transform: A.IAAPerspective
              scale: [0.02, 0.05]
            - transform: A.OneOf
              transforms:
                - transform: A.HueSaturationValue
                - transform: A.ToGray
                - transform: A.RGBShift
            - transform: A.RandomBrightnessContrast
              brightness_limit: 0.5
              contrast_limit: 0.5
            - transform: A.RandomGamma
            - transform: A.CLAHE
            - transform: A.ImageCompression
              quality_lower: 50
        - &post_transforms
          transform: A.Compose
          transforms:
            - transform: A.Normalize
            - transform: catalyst.ToTensor
    valid:
      transform: A.Compose
      transforms:
        - *pre_transforms
        - *post_transforms
    infer:
      transform: A.Compose
      transforms:
        - *pre_transforms
        - *post_transforms

  criterion_params:
    _key_value: True

    class:
      criterion: FocalLossMultiClass



  stage1:
    state_params:
      num_epochs: 8

    optimizer_params:
      # optimizer: Lookahead
      # base_optimizer_params:
      optimizer: Adam
      lr: 0.001
      weight_decay: 0.0001

    scheduler_params:
      scheduler: MultiStepLR
      milestones: [8]
      gamma: 0.3

  # tune whole network
  stage2:
    state_params:
      num_epochs: 24

    optimizer_params:
      # optimizer: Lookahead
      # base_optimizer_params:
      optimizer: Adam
      lr: 0.0003

    scheduler_params:
      scheduler: MultiStepLR
      milestones: [12, 20]
      gamma: 0.3

  callbacks_params:
    loss_class:
      callback: CriterionCallback
      input_key: targets
      output_key: logits
      prefix: loss_class
      criterion_key: class

    accuracy_class:
      callback: AccuracyCallback
      input_key: targets
      output_key: logits
      prefix: accuracy_class
      num_classes: *num_classes
    auc_class:
      callback: AUCCallback
      input_key: targets_one_hot
      output_key: logits
      prefix: auc_class
      class_names: *class_names
      num_classes: *num_classes
    f1_class:
      callback: F1ScoreCallback
      input_key: targets_one_hot
      output_key: logits
      activation: Softmax
    cm_class:
      callback: ConfusionMatrixCallback
      input_key: targets
      output_key: logits
      prefix: cm_class
      class_names: *class_names
      num_classes: *num_classes

    optimizer:
      callback: OptimizerCallback
      loss_key: loss_class
    scheduler:
      callback: SchedulerCallback
      reduced_metric: *reduced_metric
    saver:
      callback: CheckpointCallback
